// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyDKr9IrHjaa_4HtYIXIpC0AaE8EcIFV2z4',
  //   appId: '1:711162688751:web:7c278ad4127db6f17e971a',
  //   messagingSenderId: '711162688751',
  //   projectId: 'dummy-data-b127f',
  //   authDomain: 'dummy-data-b127f.firebaseapp.com',
  //   databaseURL: 'https://dummy-data-b127f-default-rtdb.asia-southeast1.firebasedatabase.app',
  //   storageBucket: 'dummy-data-b127f.appspot.com',
  //   measurementId: 'G-2WFBXGBRWB',
  // );

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyAvON3alTb_X716JG8VEbi-k9j-vJpnTCA',
  //   appId: '1:711162688751:android:4b9549ee3624eeae7e971a',
  //   messagingSenderId: '711162688751',
  //   projectId: 'dummy-data-b127f',
  //   databaseURL: 'https://dummy-data-b127f-default-rtdb.asia-southeast1.firebasedatabase.app',
  //   storageBucket: 'dummy-data-b127f.appspot.com',
  // );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyB7zQ82YwxkNWXohnTbi7BbgsIIStME76M',
  //   appId: '1:711162688751:ios:5c24a9f2b519eacd7e971a',
  //   messagingSenderId: '711162688751',
  //   projectId: 'dummy-data-b127f',
  //   databaseURL: 'https://dummy-data-b127f-default-rtdb.asia-southeast1.firebasedatabase.app',
  //   storageBucket: 'dummy-data-b127f.appspot.com',
  //   iosBundleId: 'com.example.notes',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyB7zQ82YwxkNWXohnTbi7BbgsIIStME76M',
  //   appId: '1:711162688751:ios:5bbac5ddfd75161e7e971a',
  //   messagingSenderId: '711162688751',
  //   projectId: 'dummy-data-b127f',
  //   databaseURL: 'https://dummy-data-b127f-default-rtdb.asia-southeast1.firebasedatabase.app',
  //   storageBucket: 'dummy-data-b127f.appspot.com',
  //   iosBundleId: 'com.example.notes.RunnerTests',
  // );

   static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'FIREBASE_WEB_API_KEY',
    appId: 'FIREBASE_WEB_APP_ID',
    messagingSenderId: 'FIREBASE_WEB_MESSAGING_SENDER_ID',
    projectId: 'FIREBASE_WEB_PROJECT_ID',
    authDomain: 'FIREBASE_WEB_AUTH_DOMAIN',
    databaseURL: 'FIREBASE_WEB_DATABASE_URL',
    storageBucket: 'FIREBASE_WEB_STORAGE_BUCKET',
    measurementId: 'FIREBASE_WEB_MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'FIREBASE_ANDROID_API_KEY',
    appId: 'FIREBASE_ANDROID_APP_ID',
    messagingSenderId: 'FIREBASE_ANDROID_MESSAGING_SENDER_ID',
    projectId: 'FIREBASE_ANDROID_PROJECT_ID',
    databaseURL: 'FIREBASE_ANDROID_DATABASE_URL',
    storageBucket: 'FIREBASE_ANDROID_STORAGE_BUCKET',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'FIREBASE_IOS_API_KEY',
    appId: 'FIREBASE_IOS_APP_ID',
    messagingSenderId: 'FIREBASE_IOS_MESSAGING_SENDER_ID',
    projectId: 'FIREBASE_IOS_PROJECT_ID',
    databaseURL: 'FIREBASE_IOS_DATABASE_URL',
    storageBucket: 'FIREBASE_IOS_STORAGE_BUCKET',
    iosBundleId: 'FIREBASE_IOS_BUNDLE_ID',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'FIREBASE_MACOS_API_KEY',
    appId: 'FIREBASE_MACOS_APP_ID',
    messagingSenderId: 'FIREBASE_MACOS_MESSAGING_SENDER_ID',
    projectId: 'FIREBASE_MACOS_PROJECT_ID',
    databaseURL: 'FIREBASE_MACOS_DATABASE_URL',
    storageBucket: 'FIREBASE_MACOS_STORAGE_BUCKET',
    iosBundleId: 'FIREBASE_MACOS_BUNDLE_ID',
  );
}
